workflows:
  unity-windows-workflow:
      name: Unity Windows Workflow
      max_build_duration: 120
      environment:
        vars:
          UNITY_HOME: C:\Program Files\Unity\Hub\Editor\2020.3.23f1\Editor
        groups:
          - unity
      scripts:
        - name: Run Unit Tests
          script: | 
            python3 run_unit_tests.py windows
        - name: Build Windows
          script: | 
            python3 export_unity.py windows
      artifacts:
        - windows/UnitTestingPong.exe
        - Logs/unity_build_*.log
