definitions:
  - &activate
    name: Activate License
    script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
  - &test
    name: Run Unit Tests
    script: $UNITY_BIN -batchmode -executeMethod Runner.RunUnitTests -logFile -nographics -projectPath .
  - &build
    name: Build
    script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.$BUILD_SCRIPT -nographics
  - &deactivate
    name: Deactivate License
    script: $UNITY_BIN -batchmode -quit -returnlicense -nographics

workflows:
  unity-mac-workflow:
      name: Unity Mac Workflow
      environment:
        groups:
          # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        vars:
          UNITY_BIN: /Applications/Unity/Hub/Editor/2020.3.20f1/Unity.app/Contents/MacOS/Unity
          BUILD_SCRIPT: BuildMac
      scripts:
        - *activate
        - *test
        - *build
      artifacts:
        - "Build/UnitTestingPong.app"
      publishing:
        scripts:
          - *deactivate

  unity-windows-workflow:
      name: Unity Windows Workflow
      environment:
        groups:
          # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        vars:
          UNITY_BIN: C:\Program Files\Unity\Hub\Editor\2020.3.23f1\Editor\Unity.exe
          BUILD_SCRIPT: BuildWindows
      scripts:
        - *activate
        - *test
        - *build
      artifacts:
        - "Build/UnitTestingPong.exe"
      publishing:
        scripts:
          - *deactivate
