workflows:
  unity-mac-workflow:
      name: Unity Mac Workflow
      max_build_duration: 120
      environment:
        groups:
          - unity
      scripts:
        - name: Run Unit Tests
          script: | 
            python3 run_unit_tests.py mac
        - name: Build Mac
          script: | 
            python3 export_unity.py mac
      artifacts:
        - "mac/UnitTestingPong.app"
        - Logs/unity_build_*.log
