workflows:
  unity-mac-workflow:
      name: Unity Mac Workflow
      instance_type: mac_mini
      max_build_duration: 120
      environment:
        vars:
          UNITY_HOME: /Applications/Unity/Hub/Editor/2020.3.20f1/Unity.app
        groups:
          - unity
      scripts:
        - name: Run Unit Tests
          script: | 
            python3 run_unit_tests.py mac
        - name: Build Mac
          script: | 
            python3 export_unity.py mac
      artifacts:
        - mac/UnitTestingPong.exe
        - Logs/unity_build_*.log
